### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by manasppanse** [INFO-526-SU24/final-project-iriscys#1]
The following is the peer review of the project proposal by - Manas P Panse - @manasppanse 

- Describe the goal of the project.
The goal of the project is to analyze the distribution of trash collected by Mr. Trash Wheel in 2022. The project aims to present the data in a visually engaging manner to raise awareness about trash pollution and highlight the effectiveness of trash interceptors.

- Describe the data used or collected.
The dataset, sourced from Tidy Tuesday 2024, contains records of trash collected by four semi-autonomous trash interceptors, including Mr. Trash Wheel, from 2014 to 2023. Each record represents a dumpster and includes details such as the date of collection, weight, volume, and quantities of different types of trash.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
The research question will be answered through data wrangling and visualization. The analysis will be divided into two parts:
a. Type of Trash Collected: The dataset will be filtered for the year 2022, and trash amounts will be summarized and visualized using waffle plots to compare the proportions of different types of trash collected by each interceptor.
b. Total Trash Collected Over Time: A new variable, total_trash, will be created to represent the sum of all types of trash collected. This will be visualized using bar charts to show the monthly variation in trash collection throughout 2022.

- Is there anything that is unclear from the proposal?
The proposal is clear and well-structured. However, it would be helpful to include more details on the specific methods and libraries that will be used for data wrangling and visualization. Additionally, specifying the criteria for selecting the variables and the choice of visualization techniques would enhance clarity.

- Provide constructive feedback on how the team might be able to improve their project.
a. Detailed Methodology - Include some explanation of the data wrangling steps and the choice of visualization methods. This will make the analysis more reproducible.
b. Interpretation and Insights - Provide more detailed interpretations of the visualizations and discuss potential implications or insights derived from the data.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
The most interesting aspect of the project is the waffleplot visualization of the distribution of different types of trash collected by Mr. Trash Wheel. I am waiting to see which colors will be used for this plot and understand the thought-process behind choosing them.

- Provide constructive feedback on any issues with file and/or code organization.
a. Code Documentation - Ensure that the code is well-documented with comments explaining each step. This will make it easier for others to understand and replicate the analysis.
b. Code Efficiency - Review the code for efficiency and optimize where possible. This might involve using vectorized operations or more efficient data manipulation techniques.

- (Optional) Any further comments or feedback?
Consider providing a brief introduction or background on the problem of trash pollution and the role of trash interceptors. This will set the context for the analysis and make the presentation more impactful. Overall, this is a well-thought-out project with a clear goal and methodology. You know what you're doing so I'm not going to say something that might shift your focus. Although, with some additional details and refinements, your project gets more presentable & potential.

**Comment by Iriscys** [comment]
- Is there anything that is unclear from the proposal?
It would be helpful to include more details on the specific methods and libraries that will be used for data wrangling and visualization.
_Added data wrangling library for data wrangling and visualization._

  Additionally, specifying the criteria for selecting the variables and the choice of visualization techniques would enhance clarity.
  _More detailed variable selection and visualiztion steps are included in proposal and will be included in the write up._

- Provide constructive feedback on how the team might be able to improve their project.
Detailed Methodology - Include some explanation of the data wrangling steps and the choice of visualization methods. This will make the analysis more reproducible.
_More detailed data wrangling steps are included in proposal and will be included in the write up._

  Interpretation and Insights - Provide more detailed interpretations of the visualizations and discuss potential implications or insights derived from the data.
  _I will be careful of this when writing the project._

- Provide constructive feedback on any issues with file and/or code organization.
Code Documentation - Ensure that the code is well-documented with comments explaining each step.
_Comments are added for every step of code._

  Code Efficiency - Review the code for efficiency and optimize where possible. This might involve using vectorized operations or more efficient data manipulation techniques.
  _I will be careful of this when writing the project code._

- Any further comments or feedback?
Consider providing a brief introduction or background on the problem of trash pollution and the role of trash interceptors.
_Added a brief background of trash pollution in Dataset section. The role trash interceptors is to collect trash in rivers, stream or other outfall._
