### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by derekriceX** [INFO-526-SU24/final-project-iriscys#2]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Derek Rice @derekriceX 
- ...

- Describe the goal of the project.
The goal of the project is to understand the volume fraction of seven different types of solid pollution collected on a river system by a trash clean up device, a Mr. Trash Wheel. This is an excellent project, or idea for a project, I've seen video of the Mr. Trash Wheel work and it is amazing, to see a system remove massive quantities of trash that would otherwise enter a marine ecosystem - so nice project selection. 

- Describe the data used or collected.
The dataset comprises sixteen variables (columns) and 933 records (rows). Each observation (row) provides the composition of trash from one of four trash interceptors. The trash is sorted into seven types: Plastic Bottles, Polystyrene, Cigarette Butts, Glass Bottles, Plastic Bags, Wrappers, Sports Balls. Each observation summarizes a collection date for a dumpster from one of the four trash interceptors and provides an overview of date of collection, weight, volume and the number of different trash collected.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

The research question to be answered is: What is the distribution of trash collected by Mr. Trash Wheel in 2022?

The research question will be answered by filtering the dataset and generating separate plots for each trash interceptor to compare the proportion of trash types collected by each trash collection machine for comparison. In addition, a new variable, total trash, will be created summing all trash collected by each trash interceptor. Plotting total trash vs. date will display the change in trash amount collected by each machine throughout 2022. 

- Is there anything that is unclear from the proposal?

I like this project; I appreciate the idea of doing what can be done to help clean up marine ecosystems and these river based trash collection system are very effective at intercepting and removing debris. I like the Plan of Attach table you included in the proposal - that table helped clarify your approach. 

- Provide constructive feedback on how the team might be able to improve their project.

I suggest you consider adding statistical analysis to your project. You could complete an Analysis of Variance (ANOVA) to determine if the machine all collect the same quanity of trash, the same volume fraction of trash types, or if the volume of trash changes as a function of season and that type of thing. 

ANOVA:
Ho: all machines collect the same amount of trash
Ha: at least one machine collects a different quantity of trash

An ANOVA could also be combined with Box Plots to graphically display a difference in means between say (a) performance of the machines or (b) types of trash collected.  

Essentially an ANOVA tests for a difference in means between two or more groups. 
Null Hypothesis Ho: all groups have the same mean
Alternative Hypothesis Ha: at least one group has a unique mean 

An ANOVA might be a nice methodology for you to add a statistical analysis component to the scope of your project. R has an excellent capability to complete an ANOVA of your data. 

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

I would be interested to know if all four machines perform similarly, and the volume fraction of trash collected by machine.  

- Provide constructive feedback on any issues with file and/or code organization.

If I remember correctly each project was to answer two questions, whereas the proposal presents only one question. You might want to verify this. 

- (Optional) Any further comments or feedback?

**Comment by Iriscys** [comment]
- Provide constructive feedback on how the team might be able to improve their project.
  An ANOVA might be a nice methodology for you to add a statistical analysis component to the scope of your project. R has an excellent capability to complete an ANOVA of your data.
  _Great idea! Thank you for suggesting the statistical details for enriching the interpretation of trash amount by each interceptor. This will be included in discussion section in the report._

- Provide constructive feedback on any issues with file and/or code organization.
  If I remember correctly each project was to answer two questions, whereas the proposal presents only one question. You might want to verify this.
  _Since I take it as an individual project, only 1 question will be answered. To be more clear, I separate the Analysis plan into Plot 1 & Plot 2._
